### ISSUE TITLE
VM set up for docker for windows

### ISSUE THREAD

**Issue by bulgae** [codeforprojects/kaideals#22]
Get VM set up with docker image to be loaded online.
Devs with window should be able to download and set up dev environment easily.

**Comment by musedivision** [comment]
OK,
So i had a go at setting up a VM image with the build env preinstalled with docker etc. Works wonders on mac (except for some issues around docker socket permissions ... sudo gives access, but of course not an ideal solution)

Have not yet tried on Windows, I am hoping there are not virtualisation issues. 

I will upload a VM image soon containing - docker pre installed for someone with windows to test out.

**Comment by musedivision** [comment]
Made check out README.md
